"""empty message

Revision ID: 14497c98077c
Revises: 21b412f2867f
Create Date: 2023-07-25 14:41:42.889385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14497c98077c'
down_revision = '21b412f2867f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
