"""empty message

Revision ID: 6f960c95a4b9
Revises: 14497c98077c
Create Date: 2023-07-26 17:20:14.208336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f960c95a4b9'
down_revision = '14497c98077c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('propostas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_propostas_id'), ['id'], unique=False)

    op.create_table('links_e_props',
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('proposta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], )
    )
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_index('ix_venda_id')

    op.drop_table('venda')
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index('ix_produto_id')

    op.drop_table('produto')
    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('venda_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venda_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'venda', ['venda_id'], ['id'])

    op.create_table('produto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=True),
    sa.Column('valor', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('custo', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index('ix_produto_id', ['id'], unique=False)

    op.create_table('venda',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desconto', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('total', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('telefone_id', sa.INTEGER(), nullable=False),
    sa.Column('produto_id', sa.INTEGER(), nullable=False),
    sa.Column('origem_id', sa.INTEGER(), nullable=False),
    sa.Column('campanha_id', sa.INTEGER(), nullable=False),
    sa.Column('canaldavenda_id', sa.INTEGER(), nullable=False),
    sa.Column('vendedor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['canaldavenda_id'], ['canal_da_venda.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['origem_id'], ['origem.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['telefone_id'], ['telefone.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.create_index('ix_venda_id', ['id'], unique=False)

    op.drop_table('links_e_props')
    with op.batch_alter_table('propostas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_propostas_id'))

    op.drop_table('propostas')
    # ### end Alembic commands ###
