"""empty message

Revision ID: 815ac1ecc87b
Revises: 
Create Date: 2023-07-19 12:19:23.050542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815ac1ecc87b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campanha_id'), ['id'], unique=False)

    op.create_table('canal_da_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canal_da_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canal_da_venda_id'), ['id'], unique=False)

    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=True),
    sa.Column('nasc', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_id'), ['id'], unique=False)

    op.create_table('forma_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forma_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forma_pagamento_id'), ['id'], unique=False)

    op.create_table('origem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('origem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_origem_id'), ['id'], unique=False)

    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('custo', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('nome', sa.String(length=25), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('hierarquia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('telefone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=13), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telefone_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telefone_telefone'), ['telefone'], unique=False)

    op.create_table('venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('telefone_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('campanha_id', sa.Integer(), nullable=False),
    sa.Column('canaldavenda_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['canaldavenda_id'], ['canal_da_venda.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['origem_id'], ['origem.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['telefone_id'], ['telefone.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venda_id'), ['id'], unique=False)

    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('formapagamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formapagamento_id'], ['forma_pagamento.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamento_data_pagamento'), ['data_pagamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamento_data_validade'), ['data_validade'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamento_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamento_id'))
        batch_op.drop_index(batch_op.f('ix_pagamento_data_validade'))
        batch_op.drop_index(batch_op.f('ix_pagamento_data_pagamento'))

    op.drop_table('pagamento')
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venda_id'))

    op.drop_table('venda')
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telefone_telefone'))
        batch_op.drop_index(batch_op.f('ix_telefone_id'))

    op.drop_table('telefone')
    op.drop_table('users')
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_id'))

    op.drop_table('produto')
    with op.batch_alter_table('origem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_origem_id'))

    op.drop_table('origem')
    with op.batch_alter_table('forma_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forma_pagamento_id'))

    op.drop_table('forma_pagamento')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_cliente_cpf'))

    op.drop_table('cliente')
    with op.batch_alter_table('canal_da_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canal_da_venda_id'))

    op.drop_table('canal_da_venda')
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campanha_id'))

    op.drop_table('campanha')
    # ### end Alembic commands ###
